name: Electron Release

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Use GitHub API
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/user

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Electron app
        run: pnpm electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate Changelog
        run: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Get the current branch name from GITHUB_REF
          echo "CURRENT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Debug CURRENT_BRANCH
        run: echo "CURRENT_BRANCH is ${{ env.CURRENT_BRANCH }}"

      - name: Push Changes
        run: |
          git push --follow-tags origin refs/heads/${{ env.CURRENT_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-builds-${{ matrix.os }}
          path: |
            build/dist/*.dmg
            build/dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}